### ISSUE TITLE
Loading locale data with require is not working

### ISSUE THREAD

**Issue by mmueller1589** [formatjs/react-intl#1250]
I'm using react-intl 2.8.0. Currently I load all the required locale data upfront via 

```
import en from 'react-intl/locale-data/en';
import de from 'react-intl/locale-data/de';
import pl from 'react-intl/locale-data/pl';
import ru from 'react-intl/locale-data/ru';
import fr from 'react-intl/locale-data/fr';
import pt from 'react-intl/locale-data/pt';
import es from 'react-intl/locale-data/es';
import ko from 'react-intl/locale-data/ko';
import zh from 'react-intl/locale-data/zh';
import it from 'react-intl/locale-data/it';
import cs from 'react-intl/locale-data/cs';
import el from 'react-intl/locale-data/el';
import hu from 'react-intl/locale-data/hu';
import id from 'react-intl/locale-data/id';
import ja from 'react-intl/locale-data/ja';
import ro from 'react-intl/locale-data/ro';
import th from 'react-intl/locale-data/th';
import tr from 'react-intl/locale-data/tr';
import vi from 'react-intl/locale-data/vi';

addLocaleData([...en,`` ...de, ...pl, ...ru, ...fr, ...pt, ...es, ...ko, ...zh,
  ...it, ...cs, ...el, ...hu, ...id, ...ja, ...ro, ...th, ...tr, ...vi]);
```

This is working fine, but it increases my bundle size. So I tried to load only the required locale data by using:

```
const localeData = require(`react-intl/locale-data/${locale}`);
addLocaleData(localeData);
```

Unfortunately I get this error message:

```
Error running template: Error: Cannot find module 'react-intl/locale-data/ru'
    at makeMissingError (packages\modules-runtime.js:222:12)
    at Module.require (packages\modules-runtime.js:241:17)
    at Module.profileWrapper [as require] (C:\Projects\lolvvv\WebApp\.meteor\local\build\programs\server\profile.js:263:16)
    at require (packages\modules-runtime.js:258:21)
    at changeLocale (imports/services/actions/index.js:28:22)
    at sink (server/ssr.jsx:42:18)
    at onPageLoad.chain.callback (packages/server-render/server-register.js:14:19)
    at promise.then (packages/server-render/server.js:28:36)
```

I use the Meteor framework with server side rendering. Looking at my node_modules folder I see the module react-intl/locale-data/ru. Is this a bug or is something wrong with my code?

**Comment by mmueller1589** [comment]
Looks like it is not possible to load modules dynamically. If I use require('react-intl/locale-data/ru') it works fine. So my question is how would I load a specific language dynamically since I don't want to load all possible locales upfront?

**Comment by mmueller1589** [comment]
I have a solution now. In case someone is interested:

I have a async function:
```
async function loadLocale(locale) {
  switch (locale) {
    case 'de':
      return await import('react-intl/locale-data/de');
    case 'pl':
      return await import('react-intl/locale-data/pl');
    case 'ru':
      return await import('react-intl/locale-data/ru');
    case 'fr':
      return await import('react-intl/locale-data/fr');
    case 'pt':
      return await import('react-intl/locale-data/pt');
    case 'es':
      return await import('react-intl/locale-data/es');
    case 'ko':
      return await import('react-intl/locale-data/ko');
    case 'zh':
      return await import('react-intl/locale-data/zh');
    case 'it':
      return await import('react-intl/locale-data/it');
    case 'cs':
      return await import('react-intl/locale-data/cs');
    case 'el':
      return await import('react-intl/locale-data/el');
    case 'hu':
      return await import('react-intl/locale-data/hu');
    case 'id':
      return await import('react-intl/locale-data/id');
    case 'ja':
      return await import('react-intl/locale-data/ja');
    case 'ro':
      return await import('react-intl/locale-data/ro');
    case 'th':
      return await import('react-intl/locale-data/th');
    case 'tr':
      return await import('react-intl/locale-data/tr');
    case 'vi':
      return await import('react-intl/locale-data/vi');
    default:
      return await import('react-intl/locale-data/en');
  };  
}
```

On the server I make all required locales available, so I'm able to render the app properly. Messages and locale is part of my redux store, provided by the server to the client via a preloaded state attached to the window.  Still I cannot hydrate on the client side the app, because I have the locale data not available. Therefore I wrapped the hydrate method by an async function:

```
async () => {
  loadLocale(store.getState().intl.locale).then(localeData => {
    addLocaleData(localeData.default)
    hydrate(
      <HelmetProvider>
        <Provider store={store}>
          <ReduxIntlProvider>
            <App />
          </ReduxIntlProvider>
        </Provider>
      </HelmetProvider>,
      document.getElementById('root'),
    );
  });
});
```

Opinions on this one?
