### ISSUE TITLE
console error when testing FormattedRelativeTime

### ISSUE THREAD

**Issue by quantson** [formatjs/react-intl#1485]
### Current behavior

When testing `FormattedRelativeTime`, I get the following console.error (test is passing, i.e. snapshot gets written, but it fallbacks to the `value` passed to `FormattedRelativeTime`)

```
  console.error node_modules/react-intl/dist/utils.js:59
    [React Intl] Error formatting relative time.
    TypeError: Cannot read property 'bind' of undefined
        at /Users/quentin/shipup/app-shipup/node_modules/intl-format-cache/dist/index.js:40:52
        at getFormatter (/Users/quentin/shipup/app-shipup/node_modules/react-intl/dist/formatters/relativeTime.js:11:12)
        at formatRelativeTime (/Users/quentin/shipup/app-shipup/node_modules/react-intl/dist/formatters/relativeTime.js:19:16)
        at /Users/quentin/shipup/app-shipup/node_modules/react-intl/dist/components/relative.js:174:41
        at updateContextConsumer (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7582:19)
        at beginWork (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7770:14)
        at performUnitOfWork (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11413:12)
        at workLoop (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11445:24)
        at renderRoot (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11528:7)
        at performWorkOnRoot (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12416:7)
        at performWork (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12328:7)
        at performSyncWork (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12302:3)
        at requestWork (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12171:5)
        at scheduleWork (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11986:5)
        at scheduleRootUpdate (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12585:3)
        at updateContainerAtExpirationTime (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12613:10)
        at updateContainer (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12624:10)
        at Object.create (/Users/quentin/shipup/app-shipup/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13057:5)
        at Object.create (/Users/quentin/shipup/app-shipup/failingTest.spec.js:9:8)
        at Object.asyncJestTest (/Users/quentin/shipup/app-shipup/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
        at resolve (/Users/quentin/shipup/app-shipup/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
        at new Promise (<anonymous>)
        at mapper (/Users/quentin/shipup/app-shipup/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at promise.then (/Users/quentin/shipup/app-shipup/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
```
### Step to reproduce

Here's a failing test
```
import React from 'react';
import { IntlProvider } from 'react-intl';
import renderer from 'react-test-renderer';
import { FormattedRelativeTime } from 'react-intl';

describe('<FormattedRelativeTime />', () => {
  test('renders well', () => {
    const tree = renderer
      .create(
        <IntlProvider locale="en">
          <FormattedRelativeTime value={-20} numeric="auto" />
        </IntlProvider>
      )
      .toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```
### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.2.1 |
|      `npm ls react` | 16.8.6 |

**Comment by longlho** [comment]
Looks like you're missing `Intl.RelativeTimeFormat` polyfill https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#runtime-requirements

**Comment by longlho** [comment]
Latest `master` should have instructions on how to polyfill embedded within the err message itself
