### ISSUE TITLE
Cannot assign to read only property '_babel' of [React Intl] Message failed to parse

### ISSUE THREAD

**Issue by haf** [formatjs/react-intl#279]
```
ERROR in page.js
Module build failed: TypeError: js/accounts/forgot.js: Error is not a function
    at File.buildCodeFrameError (node_modules/babel-core/lib/transformation/file/index.js:408:15)
    at NodePath.buildCodeFrameError (node_modules/babel-traverse/lib/path/index.js:148:26)
    at node_modules/babel-plugin-react-intl/lib/index.js:68:37
    at Array.reduce (native)
    at createMessageDescriptor (node_modules/babel-plugin-react-intl/lib/index.js:45:26)
    at PluginPass.JSXOpeningElement (node_modules/babel-plugin-react-intl/lib/index.js:164:38)
    at newFn (node_modules/babel-traverse/lib/visitors.js:276:19)
    at NodePath._call (node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:197:19)
    at Function.traverse.node (node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:197:19)
    at Function.traverse.node (node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:153:16)
 @ ./js/routes.js 17:13-41
```

And when throwing the `msg` directly:

```
throw msg;
var err = new Error(msg);
```

This becomes the error:

```
Module build failed: TypeError: Cannot assign to read only property '_babel' of [React Intl] Message failed to parse. See: http://formatjs.io/guides/message-syntax/
```

Can be triggered with

```
        <FormattedHTMLMessage
          id='accounts.forgot.anAsideTextHtml'
          defaultMessage="\&quot;"
          description="" />
```

**Comment by ericf** [comment]
You likely just need to remove the leading backslash. I can look into why the error message is so odd.

**Comment by haf** [comment]
Yes, I discovered while debugging. Figured you'd want to know about the error in your error handling.
