### ISSUE TITLE
Can´t make it work on server side rendering: Error walking your react tree (could not find required `intl` object)

### ISSUE THREAD

**Issue by renatonmendes** [formatjs/react-intl#927]
I´m trying to make it work using server side rendering [(based on react-universally)](https://github.com/ctrlplusb/react-universally):

```

`/* eslint-disable global-require */

import React from 'react';
import { render } from 'react-dom';
import { AsyncComponentProvider } from 'react-async-component';
import { AppContainer } from 'react-hot-loader';

import { IntlProvider, addLocaleData } from 'react-intl';
import en from 'react-intl/locale-data/en';
import pt from 'react-intl/locale-data/pt';
import es from 'react-intl/locale-data/es';

import './polyfills';

import ReactHotLoader from './components/ReactHotLoader';
import DemoApp from '../shared/components/DemoApp';

import localeData from '../../intl/messages.json';

const container = document.querySelector('#app');

addLocaleData([...en,...pt,...es]);

const language = (navigator.languages && navigator.languages[0]) ||
                  navigator.language ||
                  navigator.userLanguage;

const languageWithoutRegionCode = language.toLowerCase().split(/[_-]+/)[0];

const messages = localeData[languageWithoutRegionCode] || localeData[language] || localeData.en;

function renderApp(TheApp) {
  const app = (
      <IntlProvider locale={language} messages={messages}>
            <TheApp />
      </IntlProvider>
  );

  asyncBootstrapper(app).then(() => render(app, container));
}

renderApp(DemoApp);

if (process.env.BUILD_FLAG_IS_DEV === 'true' && module.hot) {
  module.hot.accept('./index.js');
  module.hot.accept('../shared/components/DemoApp', () => {
    renderApp(require('../shared/components/DemoApp').default);
  });
}
```
`
My DemoApp:

```
import 'normalize.css/normalize.css';

import React from 'react';

import { FormattedMessage } from 'react-intl';

function DemoApp() {
  return (
    <div>
      <h1>This is a test</h1>
      <FormattedMessage id={'Header.Title'} defaultText={'This is a header test title'} />
    </div>
  );
}

export default DemoApp;

```

And the webpack configuration:
```
{
    "entry": {
        "index": [
            "regenerator-runtime/runtime",
            "react-hot-loader/patch",
            "webpack-hot-middleware/client?reload=true&path=http://localhost:7331/__webpack_hmr",
            "D:\\9. DEV\\WORKSPACE\\mz-boilerplate-intl\\src\\client\\index.js"
        ]
    },
    "output": {
        "path": "D:\\9. DEV\\WORKSPACE\\mz-boilerplate-intl\\build\\client",
        "filename": "[name].js",
        "chunkFilename": "[name]-[chunkhash].js",
        "libraryTarget": "var",
        "publicPath": "http://localhost:7331/client/"
    },
    "target": "web",
    "node": {
        "__dirname": true,
        "__filename": true
    },
    "devtool": "source-map",
    "performance": false,
    "resolve": {
        "extensions": [
            ".js",
            ".jsx",
            ".json"
        ],
        "alias": {
            "modernizr$": "D:\\9. DEV\\WORKSPACE\\mz-boilerplate-intl\\.modernizrrc"
        }
    },
    "externals": [],
    "plugins": [
        {},
        {
            "keys": [
                "NODE_ENV",
                "BUILD_FLAG_IS_CLIENT",
                "BUILD_FLAG_IS_SERVER",
                "BUILD_FLAG_IS_NODE",
                "BUILD_FLAG_IS_DEV"
            ],
            "defaultValues": {
                "NODE_ENV": "development",
                "BUILD_FLAG_IS_CLIENT": "true",
                "BUILD_FLAG_IS_SERVER": "false",
                "BUILD_FLAG_IS_NODE": "false",
                "BUILD_FLAG_IS_DEV": "true"
            }
        },
        {
            "options": {
                "path": "D:\\9. DEV\\WORKSPACE\\mz-boilerplate-intl\\build\\client",
                "filename": "assets.json",
                "prettyPrint": false,
                "update": false,
                "fullPath": true
            }
        },
        {},
        {
            "fullBuildTimeout": 200
        },
        {
            "name": "HappyPack",
            "state": {
                "started": false,
                "loaders": [],
                "baseLoaderRequest": "",
                "foregroundThreadPool": null,
                "verbose": false,
                "debug": false
            },
            "config": {
                "id": "happypack-javascript",
                "compilerId": "default",
                "tempDir": ".happypack",
                "threads": 4,
                "cache": true,
                "cacheContext": {},
                "verbose": false,
                "enabled": true,
                "loaders": [
                    {
                        "path": "babel-loader",
                        "query": {
                            "babelrc": false,
                            "presets": [
                                "react",
                                "stage-3",
                                [
                                    "env",
                                    {
                                        "es2015": {
                                            "modules": false
                                        }
                                    }
                                ]
                            ],
                            "plugins": [
                                "react-hot-loader/babel",
                                "transform-react-jsx-self",
                                "transform-react-jsx-source",
                                [
                                    "react-intl",
                                    {
                                        "messagesDir": "./intl",
                                        "enforceDescriptions": false
                                    }
                                ]
                            ]
                        }
                    }
                ]
            },
            "id": "happypack-javascript"
        },
        {
            "name": "HappyPack",
            "state": {
                "started": false,
                "loaders": [],
                "baseLoaderRequest": "",
                "foregroundThreadPool": null,
                "verbose": false,
                "debug": false
            },
            "config": {
                "id": "happypack-devclient-css",
                "compilerId": "default",
                "tempDir": ".happypack",
                "threads": 4,
                "cache": true,
                "cacheContext": {},
                "verbose": false,
                "enabled": true,
                "loaders": [
                    "style-loader",
                    {
                        "path": "css-loader",
                        "query": {
                            "sourceMap": true
                        }
                    }
                ]
            },
            "id": "happypack-devclient-css"
        }
    ],
    "module": {
        "rules": [
            {
                "test": {},
                "loader": "happypack/loader?id=happypack-javascript",
                "include": [
                    "D:\\9. DEV\\WORKSPACE\\mz-boilerplate-intl\\src\\client",
                    "D:\\9. DEV\\WORKSPACE\\mz-boilerplate-intl\\src\\shared",
                    "D:\\9. DEV\\WORKSPACE\\mz-boilerplate-intl\\config"
                ]
            },
            {
                "test": {},
                "loaders": [
                    "happypack/loader?id=happypack-devclient-css"
                ]
            },
            {
                "test": {},
                "loader": "file-loader",
                "query": {
                    "publicPath": "http://localhost:7331/client/",
                    "emitFile": true
                }
            },
            {
                "test": {},
                "loader": "modernizr-loader"
            },
            {
                "test": {},
                "loader": "modernizr-loader!json-loader"
            }
        ]
    }
}

```
I´m getting the following error:

```
Error walking your react tree
{ Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at invariant (D:\9. DEV\WORKSPACE\mz-boilerplate-intl\node_modules\invariant\invariant.js:42:15)
    at invariantIntlContext (D:\9. DEV\WORKSPACE\mz-boilerplate-intl\node_modules\react-intl\lib\index.js:356:5)
    at new FormattedMessage (D:\9. DEV\WORKSPACE\mz-boilerplate-intl\node_modules\react-intl\lib\index.js:1406:9)
    at D:\9. DEV\WORKSPACE\mz-boilerplate-intl\node_modules\react-tree-walker\commonjs\index.js:132:24
    at reactTreeWalker (D:\9. DEV\WORKSPACE\mz-boilerplate-intl\node_modules\react-tree-walker\commonjs\index.js:71:10)
    at mapper (D:\9. DEV\WORKSPACE\mz-boilerplate-intl\node_modules\react-tree-walker\commonjs\index.js:89:29)
    at D:\9. DEV\WORKSPACE\mz-boilerplate-intl\node_modules\react-tree-walker\commonjs\index.js:53:28
    at D:\9. DEV\WORKSPACE\mz-boilerplate-intl\node_modules\react-tree-walker\commonjs\index.js:39:14 name: 'Invariant Violation', framesToPop: 1 }
(node:5072) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

```

Even with the error, the correct message is shown at screen.

No idea of what´s happening here. Need help please. If I remove the <FormattedMessage> component it runs with no errors (of course not showing the message), what means my webpack configuration and intl loading is working fine.

**Comment by aarosil** [comment]
You need to have `IntlProvider` component at your root

**Comment by renatonmendes** [comment]
Isn´t the code below doing it ?

```
function renderApp(TheApp) {
  const app = (
      <IntlProvider locale={language} messages={messages}>
            <TheApp />
      </IntlProvider>
  );

```

**Comment by sheraz-sarwar** [comment]
I was having a similar issue attempting to render server-side using Express. On further inspection, I spotted that I hadn't included the <IntlProvider> component in my server script. I note that you've not included the code for your server so it's quite possible that you've got the same problem. I've not used react-universally but a quick glance through the codebase suggests this is the script you'll need to amend (or at least something similar):

[https://github.com/ctrlplusb/react-universally/blob/master/server/middleware/reactApplication/index.js](https://github.com/ctrlplusb/react-universally/blob/master/server/middleware/reactApplication/index.js)

Here, you'll want to wrap the <StaticRouter> with the same <IntlProvider> you're using in the renderApp() function of your index file. My set up is obviously different but this approach fixed it for me so it's worth a try.

**Comment by oyeanuj** [comment]
@renatonmendes Did you end up integrating `react-universally` with `react-intl`? If yes, could you share your results/fork?
